CONFIG_PRINTK=y
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_STDOUT_CONSOLE=y

# Enable support for the HD44780 LCD display
CONFIG_AUXDISPLAY=y
CONFIG_AUXDISPLAY_HD44780=y
CONFIG_GPIO_PCF857X=y

# Enable 1-Wire support for DS18B20 temperature sensor
CONFIG_W1=y
CONFIG_SENSOR=y

# Ambient temperature sensor support
CONFIG_TMP112=y

# for debugging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_UART_CONSOLE=y